### ISSUE TITLE
As user, I want to be able to conveniently start a tracker that counts the spent time for me.

### ISSUE THREAD

**Issue by fre-ben** [fre-ben/remote-assignment-timetracker#2]
Acceptance criteria:

- [x] The tracker should start tracking with a single click.
- [x] Time is displayed in a user friendly format, specifically hh:mm:ss.
- [x] The timer can be paused and resumed.
